// Conditional Tests: Write a series of conditional tests. Print a statement describing each test and your prediction for the results of each test. Your code should look something like this:
var x = 5;
var y = 10;
console.log("Is x == y? I predict False.");
console.log(x == y);
console.log("Is x > y? I predict False.");
console.log(x > y);
console.log("Is x < y? I predict True.");
console.log(x < y);
console.log("Is x >= y? I predict False.");
console.log(x >= y);
console.log("Is x <= y? I predict True.");
console.log(x <= y);
var str1 = "hello";
var str2 = "world";
console.log("Is str1 == str2? I predict False.");
console.log(str1 == str2);
console.log("Is str1 equalsIgnoreCase str2? I predict False.");
console.log(str1.toLowerCase() == str2.toLowerCase());
console.log("Is str1 equals str2? I predict False.");
console.log(str1 === str2);
